DOCKER-394 Introduce SOLR_BACKUP_DIR variable with default
xenit-eu/docker-solr pull request #60
Opened 2021-12-15 12:33 UTC by Ranecdev

2021-12-15 15:54 UTC, wimfabri approved these changes

2021-12-15 22:47 UTC, anghelutar commented
Backup folders are created in the init scripts, both for solr4 and solr6.
The code from the Dockerfile is redundant, can be removed.

2021-12-16 08:11 UTC, vierbergenlars requested changes

2021-12-16 08:11 UTC, vierbergenlars commented on README.md
> +| SOLR_BACKUP_DIR | solr.backup.dir | | /opt/alfresco-search-services/data/solr6Backup | solr6 ASS v2* only |
You are using this variable in the generic `Dockerfile.solr6` below.

That means it is not ASS 2.x only.

2021-12-20 09:14 UTC, vierbergenlars approved these changes

2021-12-20 09:32 UTC, merged

2021-12-20 12:54 UTC, anghelutar commented
There are a number of problems with this PR:
1) Variable solr.backup.dir appeared in ASS 2.0.2. Current check will add the variable for any ASS 2*.
2) Path to the core (and to the shard in the case of a sharded setup) needs to be added to the backup variable.
3) There is no point to have any backup-related variable in the Dockerfile, it is duplicated in the init scripts.
PR https://github.com/xenit-eu/docker-solr/pull/61 should fix these.